# Available languages
LANG_FR = 'fr'
MASCULINE = 1
FEMININE = 2

NUMBERS = {
    LANG_FR: {
        'plus': '-',
        'times': '-',
        'ordinal suffix': 'ième',
        # chiffres
        0: ('zéro', 'zéroïème'),
        1: ('un', 'premier', 'première'),
        2: ('deux',),
        3: ('trois',),
        4: ('quatre', 'quatrième'),
        5: ('cinq', 'cinquième'),
        6: ('six',),
        7: ('sept',),
        8: ('huit',),
        9: ('neuf', 'neuvième'),
        # dizaines
        10: ('dix',),
        11: ('onze', 'onzième'),
        12: ('douze', 'douzième'),
        13: ('treize', 'treizième'),
        14: ('quatorze', 'quatorzième'),
        15: ('quinze', 'quinzième'),
        16: ('seize', 'seizième'),
        19: ('dix-neuf', 'dix-neuvième'),
        20: ('vingt',),
        21: ('vingt-et-un',),
        30: ('trente', 'trentième'),
        31: ('trente-et-un',),
        40: ('quarante', 'quarantième'),
        41: ('quarante-et-un',),
        50: ('cinquante', 'cinquantième'),
        51: ('cinquante-et-un',),
        60: ('soixante', 'soixantième'),
        61: ('soixante-et-un',),
        70: ('soixante-dix',),
        71: ('soixante-et-onze', 'soixante-et-onzième'),
        72: ('soixante-douze', 'soixante-douzième'),
        73: ('soixante-treize', 'soixante-treizième'),
        74: ('soixante-quatorze', 'soixante-quatorzième'),
        75: ('soixante-quinze', 'soixante-quinzième'),
        76: ('soixante-seize', 'soixante-seizième'),
        77: ('soixante-dix-sept',),
        78: ('soixante-dix-huit',),
        79: ('soixante-dix-neuf', 'soixante-dix-neuvième'),
        80: ('quatre-vingt',),
        90: ('quatre-vingt-dix',),
        91: ('quatre-vingt-onze', 'quatre-vingt-onzième'),
        92: ('quatre-vingt-douze', 'quatre-vingt-douzième'),
        93: ('quatre-vingt-treize', 'quatre-vingt-treizième'),
        94: ('quatre-vingt-quatorze', 'quatre-vingt-quatorzième'),
        95: ('quatre-vingt-quinze', 'quatre-vingt-quinzième'),
        96: ('quatre-vingt-seize', 'quatre-vingt-seizième'),
        97: ('quatre-vingt-dix-sept',),
        98: ('quatre-vingt-dix-huit',),
        99: ('quatre-vingt-dix-neuf', 'quatre-vingt-neuvième'),
        # centaines et milliers
        100: ('cent',),
        101: ('cent-un', 'cent-unième',),
        201: ('deux-cent-un', 'deux-cent-unième',),
        301: ('trois-cent-un', 'trois-cent-unième',),
        401: ('quatre-cent-un', 'quatre-cent-unième',),
        501: ('cinq-cent-un', 'cinq-cent-unième',),
        601: ('six-cent-un', 'six-cent-unième',),
        701: ('sept-cent-un', 'sept-cent-unième',),
        801: ('huit-cent-un', 'huit-cent-unième',),
        901: ('neuf-cent-un', 'neuf-cent-unième',),
        1000: ('mille', 'millième'),
        1001: ('mille-un', 'mille-et-unième'),
    }
}
