return {
  { "File:Samediggi03.jpg", "[[Norgga Sámediggi]] [[Kárášjohka|Kárášjogas]]" },
  { "File:Chrysantheme rot tautropfen -20191024-RM-102058.jpg", "''Chrysanthemum × morifolium''" },
  { "File:Amanda Delara (29519019388).jpg", "[[Amanda Delara]] [[Riddu Riđđu|Riddu Riđus]]" },
  { "File:Buffy Sainte-Marie lávvu Riddu Riđđu 2019 29.jpg", "Illuzina málen [[Buffy Sainte-Marie]] lávvu [[Riddu Riđđu]]-festiválas 2019" },
  { "File:Lavvo med kunst på Riddu Riđđu 2019.jpg" },
  { "File:View from a ridge between Segla and Hesten, Senja, Norway, 2014 August.jpg" },
  { "File:Aurora borealis above Storfjorden and the Lyngen Alps in moonlight, 2012 March.jpg" },
  { "File:View to Lyngenfjorden from east coast, 2011 06.jpg" },
  { "File:Storfjorden autumn, 2009 09.jpg" },
  { "File:Lenangstindane and Jægervasstindane in Lyngen, 2012 March.jpg" },
  { "File:Oksneset and Ersfjorden from Tungeneset in low sunlight, Senja, 2012 October - 2.jpg" },
  { "File:View to Sifjorden from Sifjord, Senja, Troms, Norway in 2014 August.jpg" },
  { "File:Autumn landscape near Gullesfjordbotn, Hinnøya, 2010 September.jpg" },
  { "File:Frosty Raftsundet landscape with Trolltindan in morning, 2012 October.JPG" },
  { "File:Okshornan from Tungeneset, 2015 September - 3.jpg" },
  { "File:Distorting water reflections at Digermulen port, Hinnøya, Norway, 2015 September.jpg" },
  { "File:Herd of reindeer at Hamningberg, 2012 June.JPG" },
  { "File:Norwegen Langfjordelva (Laggu) Gamvik 1290368.jpg" },
  { "File:Seggelskaret walls and Segla by Mefjorden, Senja, Norway, 2015 September.jpg" },
  { "File:Fjølhaugen in Senja, Troms, Norway, 2015 September.jpg" },
  { "File:Virmalised 17.03.15.jpg", "Guovssahasat [[Estteeana|Estteeatnamis]]" },
  { "File:Virmalised 18.03.15 (2).jpg", "Guovssahasat [[Estteeana|Estteeatnamis]]" },
  { "File:Aurora in Abisko near Torneträsk.jpg", "Guovssahasat [[Ábeskovvu]]s" },
  { "File:Njommelsaska i Lappland by Carl Svantje Hallbeck.jpg" },
  { "File:20070818-0001-strolling reindeer.jpg" },
  { "File:Kiirunavaara September 2017 10.jpg" },
  { "File:Kiruna kyrka September 2017 04.jpg", "Girona girku" },
  { "File:Runebomme or Sami drum 02.jpg" },
}
