return {
  [0xE0001] = { en = "LANGUAGE TAG", fr = "TAG DE LANGUE" },
  [0xE0020] = { en = "TAG SPACE", fr = "ESPACE TAG" },
  [0xE0021] = { en = "TAG EXCLAMATION MARK", fr = "POINT D’EXCLAMATION" },
  [0xE0022] = { en = "TAG QUOTATION MARK", fr = "TAG GUILLEMET" },
  [0xE0023] = { en = "TAG NUMBER SIGN", fr = "SIGNE DU NUMÉRO D’ÉTIQUETTE" },
  [0xE0024] = { en = "TAG DOLLAR SIGN", fr = "TAG DOLLAR TAG" },
  [0xE0025] = { en = "TAG PERCENT SIGN", fr = "TAG POURCENTAGE SIGNE" },
  [0xE0026] = { en = "TAG AMPERSAND", fr = "TAG ESPERLUETTE" },
  [0xE0027] = { en = "TAG APOSTROPHE", fr = "TAG APOSTROPHE" },
  [0xE0028] = { en = "TAG LEFT PARENTHESIS", fr = "TAG PARENTHÈSE GAUCHE" },
  [0xE0029] = { en = "TAG RIGHT PARENTHESIS", fr = "TAG RIGHT PARENTHESIS" },
  [0xE002A] = { en = "TAG ASTERISK", fr = "TAG ASTÉRISQUE" },
  [0xE002B] = { en = "TAG PLUS SIGN", fr = "TAG PLUS SIGN" },
  [0xE002C] = { en = "TAG COMMA", fr = "TAG VIRGULE" },
  [0xE002D] = { en = "TAG HYPHEN-MINUS", fr = "TAG HYPHEN-MINUS" },
  [0xE002E] = { en = "TAG FULL STOP", fr = "TAG FULL STOP" },
  [0xE002F] = { en = "TAG SOLIDUS", fr = "TAG SOLIDUS" },
  [0xE0030] = { en = "TAG DIGIT ZERO", fr = "TAG DIGIT ZERO" },
  [0xE0031] = { en = "TAG DIGIT ONE", fr = "TAG DIGIT ONE" },
  [0xE0032] = { en = "TAG DIGIT TWO", fr = "TAG DIGIT TWO" },
  [0xE0033] = { en = "TAG DIGIT THREE", fr = "TAG CHIFFRE TROIS" },
  [0xE0034] = { en = "TAG DIGIT FOUR", fr = "TAG DIGIT FOUR" },
  [0xE0035] = { en = "TAG DIGIT FIVE", fr = "TAG DIGIT FIVE" },
  [0xE0036] = { en = "TAG DIGIT SIX", fr = "TAG DIGIT SIX" },
  [0xE0037] = { en = "TAG DIGIT SEVEN", fr = "TAG DIGIT SEVEN" },
  [0xE0038] = { en = "TAG DIGIT EIGHT", fr = "TAG DIGIT HUIT" },
  [0xE0039] = { en = "TAG DIGIT NINE", fr = "TAG DIGIT NINE" },
  [0xE003A] = { en = "TAG COLON", fr = "TAG COLON" },
  [0xE003B] = { en = "TAG SEMICOLON", fr = "TAG POINT-VIRGULE" },
  [0xE003C] = { en = "TAG LESS-THAN SIGN", fr = "TAG MOINS-QUE SIGNE" },
  [0xE003D] = { en = "TAG EQUALS SIGN", fr = "TAG ÉGAL SIGNE" },
  [0xE003E] = { en = "TAG GREATER-THAN SIGN", fr = "TAG SUPÉRIEUR-QUE SIGNE" },
  [0xE003F] = { en = "TAG QUESTION MARK", fr = "POINT D’INTERROGATION" },
  [0xE0040] = { en = "TAG COMMERCIAL AT", fr = "TAG COMMERCIAL AT" },
  [0xE0041] = { en = "TAG LATIN CAPITAL LETTER A", fr = "TAG LETTRE MAJUSCULE LATINE A" },
  [0xE0042] = { en = "TAG LATIN CAPITAL LETTER B", fr = "TAG LATIN LETTRE CAPITALE B" },
  [0xE0043] = { en = "TAG LATIN CAPITAL LETTER C", fr = "TAG LETTRE MAJUSCULE LATINE C" },
  [0xE0044] = { en = "TAG LATIN CAPITAL LETTER D", fr = "TAG LETTRE MAJUSCULE LATINE D" },
  [0xE0045] = { en = "TAG LATIN CAPITAL LETTER E", fr = "TAG LETTRE MAJUSCULE LATINE E" },
  [0xE0046] = { en = "TAG LATIN CAPITAL LETTER F", fr = "TAG LETTRE MAJUSCULE LATINE F" },
  [0xE0047] = { en = "TAG LATIN CAPITAL LETTER G", fr = "TAG LETTRE MAJUSCULE LATINE G" },
  [0xE0048] = { en = "TAG LATIN CAPITAL LETTER H", fr = "TAG LETTRE MAJUSCULE LATINE H" },
  [0xE0049] = { en = "TAG LATIN CAPITAL LETTER I", fr = "TAG LETTRE MAJUSCULE LATINE I" },
  [0xE004A] = { en = "TAG LATIN CAPITAL LETTER J", fr = "TAG LETTRE MAJUSCULE LATINE J" },
  [0xE004B] = { en = "TAG LATIN CAPITAL LETTER K", fr = "TAG LETTRE MAJUSCULE LATINE K" },
  [0xE004C] = { en = "TAG LATIN CAPITAL LETTER L", fr = "TAG LETTRE MAJUSCULE LATINE L" },
  [0xE004D] = { en = "TAG LATIN CAPITAL LETTER M", fr = "TAG LETTRE MAJUSCULE LATINE M" },
  [0xE004E] = { en = "TAG LATIN CAPITAL LETTER N", fr = "TAG LETTRE MAJUSCULE LATINE N" },
  [0xE004F] = { en = "TAG LATIN CAPITAL LETTER O", fr = "TAG LETTRE MAJUSCULE LATINE O" },
  [0xE0050] = { en = "TAG LATIN CAPITAL LETTER P", fr = "TAG LETTRE MAJUSCULE LATINE P" },
  [0xE0051] = { en = "TAG LATIN CAPITAL LETTER Q", fr = "TAG LETTRE MAJUSCULE LATINE Q" },
  [0xE0052] = { en = "TAG LATIN CAPITAL LETTER R", fr = "TAG LETTRE MAJUSCULE LATINE R" },
  [0xE0053] = { en = "TAG LATIN CAPITAL LETTER S", fr = "TAG LETTRE MAJUSCULE LATINE S" },
  [0xE0054] = { en = "TAG LATIN CAPITAL LETTER T", fr = "TAG LETTRE MAJUSCULE LATINE T" },
  [0xE0055] = { en = "TAG LATIN CAPITAL LETTER U", fr = "TAG LETTRE MAJUSCULE LATINE U" },
  [0xE0056] = { en = "TAG LATIN CAPITAL LETTER V", fr = "TAG LETTRE MAJUSCULE LATINE V" },
  [0xE0057] = { en = "TAG LATIN CAPITAL LETTER W", fr = "TAG LETTRE MAJUSCULE LATINE W" },
  [0xE0058] = { en = "TAG LATIN CAPITAL LETTER X", fr = "TAG LETTRE MAJUSCULE LATINE X" },
  [0xE0059] = { en = "TAG LATIN CAPITAL LETTER Y", fr = "TAG LETTRE MAJUSCULE LATINE Y" },
  [0xE005A] = { en = "TAG LATIN CAPITAL LETTER Z", fr = "TAG LETTRE MAJUSCULE LATINE Z" },
  [0xE005B] = { en = "TAG LEFT SQUARE BRACKET", fr = "SUPPORT CARRÉ GAUCHE" },
  [0xE005C] = { en = "TAG REVERSE SOLIDUS", fr = "TAG REVERSE SOLIDUS" },
  [0xE005D] = { en = "TAG RIGHT SQUARE BRACKET", fr = "SUPPORT CARRÉ DROIT" },
  [0xE005E] = { en = "TAG CIRCUMFLEX ACCENT", fr = "ÉTIQUETTE CIRCUMFLEX ACCENT" },
  [0xE005F] = { en = "TAG LOW LINE", fr = "TAG LOW LINE" },
  [0xE0060] = { en = "TAG GRAVE ACCENT", fr = "TAG GRAVE ACCENT" },
  [0xE0061] = { en = "TAG LATIN SMALL LETTER A", fr = "TAG LATIN PETITE LETTRE A" },
  [0xE0062] = { en = "TAG LATIN SMALL LETTER B", fr = "TAG LATIN PETITE LETTRE B" },
  [0xE0063] = { en = "TAG LATIN SMALL LETTER C", fr = "TAG LATIN PETITE LETTRE C" },
  [0xE0064] = { en = "TAG LATIN SMALL LETTER D", fr = "TAG LATIN PETITE LETTRE D" },
  [0xE0065] = { en = "TAG LATIN SMALL LETTER E", fr = "TAG LATIN PETITE LETTRE E" },
  [0xE0066] = { en = "TAG LATIN SMALL LETTER F", fr = "TAG LATIN PETITE LETTRE F" },
  [0xE0067] = { en = "TAG LATIN SMALL LETTER G", fr = "TAG LATIN PETITE LETTRE G" },
  [0xE0068] = { en = "TAG LATIN SMALL LETTER H", fr = "TAG LATIN PETITE LETTRE H" },
  [0xE0069] = { en = "TAG LATIN SMALL LETTER I", fr = "TAG LATIN PETITE LETTRE I" },
  [0xE006A] = { en = "TAG LATIN SMALL LETTER J", fr = "TAG LATIN PETITE LETTRE J" },
  [0xE006B] = { en = "TAG LATIN SMALL LETTER K", fr = "TAG LATIN PETITE LETTRE K" },
  [0xE006C] = { en = "TAG LATIN SMALL LETTER L", fr = "TAG LATIN PETITE LETTRE L" },
  [0xE006D] = { en = "TAG LATIN SMALL LETTER M", fr = "TAG LATIN PETITE LETTRE M" },
  [0xE006E] = { en = "TAG LATIN SMALL LETTER N", fr = "TAG LATIN PETITE LETTRE N" },
  [0xE006F] = { en = "TAG LATIN SMALL LETTER O", fr = "TAG LATIN PETITE LETTRE O" },
  [0xE0070] = { en = "TAG LATIN SMALL LETTER P", fr = "TAG LATIN PETITE LETTRE P" },
  [0xE0071] = { en = "TAG LATIN SMALL LETTER Q", fr = "TAG LATIN PETITE LETTRE Q" },
  [0xE0072] = { en = "TAG LATIN SMALL LETTER R", fr = "TAG LATIN PETITE LETTRE R" },
  [0xE0073] = { en = "TAG LATIN SMALL LETTER S", fr = "TAG LATIN PETITE LETTRE S" },
  [0xE0074] = { en = "TAG LATIN SMALL LETTER T", fr = "TAG LATIN PETITE LETTRE T" },
  [0xE0075] = { en = "TAG LATIN SMALL LETTER U", fr = "TAG LATIN PETITE LETTRE U" },
  [0xE0076] = { en = "TAG LATIN SMALL LETTER V", fr = "TAG LATIN PETITE LETTRE V" },
  [0xE0077] = { en = "TAG LATIN SMALL LETTER W", fr = "TAG LATIN PETITE LETTRE W" },
  [0xE0078] = { en = "TAG LATIN SMALL LETTER X", fr = "TAG LATIN PETITE LETTRE X" },
  [0xE0079] = { en = "TAG LATIN SMALL LETTER Y", fr = "TAG LATIN PETITE LETTRE Y" },
  [0xE007A] = { en = "TAG LATIN SMALL LETTER Z", fr = "TAG LATIN PETITE LETTRE Z" },
  [0xE007B] = { en = "TAG LEFT CURLY BRACKET", fr = "SUPPORT GAUCHE AVEC BOUCLES" },
  [0xE007C] = { en = "TAG VERTICAL LINE", fr = "TAG LIGNE VERTICALE" },
  [0xE007D] = { en = "TAG RIGHT CURLY BRACKET", fr = "ÉTIQUETTE DROITE BOUCLÉE" },
  [0xE007E] = { en = "TAG TILDE", fr = "TAG TILDE" },
  [0xE007F] = { en = "CANCEL TAG", fr = "ANNULER LE TAG" },
  --[=[
  -- The names for codepoints U+E0100 to U+E01EF are generated by a rule in
  -- [[Module:Unicode data]].
  [ 0xE0100 ] = { en = "VARIATION SELECTOR-17", fr = "" },
  [ 0xE0101 ] = { en = "VARIATION SELECTOR-18", fr = "" },
  [ 0xE0102 ] = { en = "VARIATION SELECTOR-19", fr = "" },
  [ 0xE0103 ] = { en = "VARIATION SELECTOR-20", fr = "" },
  [ 0xE0104 ] = { en = "VARIATION SELECTOR-21", fr = "" },
  [ 0xE0105 ] = { en = "VARIATION SELECTOR-22", fr = "" },
  [ 0xE0106 ] = { en = "VARIATION SELECTOR-23", fr = "" },
  [ 0xE0107 ] = { en = "VARIATION SELECTOR-24", fr = "" },
  [ 0xE0108 ] = { en = "VARIATION SELECTOR-25", fr = "" },
  [ 0xE0109 ] = { en = "VARIATION SELECTOR-26", fr = "" },
  [ 0xE010A ] = { en = "VARIATION SELECTOR-27", fr = "" },
  [ 0xE010B ] = { en = "VARIATION SELECTOR-28", fr = "" },
  [ 0xE010C ] = { en = "VARIATION SELECTOR-29", fr = "" },
  [ 0xE010D ] = { en = "VARIATION SELECTOR-30", fr = "" },
  [ 0xE010E ] = { en = "VARIATION SELECTOR-31", fr = "" },
  [ 0xE010F ] = { en = "VARIATION SELECTOR-32", fr = "" },
  [ 0xE0110 ] = { en = "VARIATION SELECTOR-33", fr = "" },
  [ 0xE0111 ] = { en = "VARIATION SELECTOR-34", fr = "" },
  [ 0xE0112 ] = { en = "VARIATION SELECTOR-35", fr = "" },
  [ 0xE0113 ] = { en = "VARIATION SELECTOR-36", fr = "" },
  [ 0xE0114 ] = { en = "VARIATION SELECTOR-37", fr = "" },
  [ 0xE0115 ] = { en = "VARIATION SELECTOR-38", fr = "" },
  [ 0xE0116 ] = { en = "VARIATION SELECTOR-39", fr = "" },
  [ 0xE0117 ] = { en = "VARIATION SELECTOR-40", fr = "" },
  [ 0xE0118 ] = { en = "VARIATION SELECTOR-41", fr = "" },
  [ 0xE0119 ] = { en = "VARIATION SELECTOR-42", fr = "" },
  [ 0xE011A ] = { en = "VARIATION SELECTOR-43", fr = "" },
  [ 0xE011B ] = { en = "VARIATION SELECTOR-44", fr = "" },
  [ 0xE011C ] = { en = "VARIATION SELECTOR-45", fr = "" },
  [ 0xE011D ] = { en = "VARIATION SELECTOR-46", fr = "" },
  [ 0xE011E ] = { en = "VARIATION SELECTOR-47", fr = "" },
  [ 0xE011F ] = { en = "VARIATION SELECTOR-48", fr = "" },
  [ 0xE0120 ] = { en = "VARIATION SELECTOR-49", fr = "" },
  [ 0xE0121 ] = { en = "VARIATION SELECTOR-50", fr = "" },
  [ 0xE0122 ] = { en = "VARIATION SELECTOR-51", fr = "" },
  [ 0xE0123 ] = { en = "VARIATION SELECTOR-52", fr = "" },
  [ 0xE0124 ] = { en = "VARIATION SELECTOR-53", fr = "" },
  [ 0xE0125 ] = { en = "VARIATION SELECTOR-54", fr = "" },
  [ 0xE0126 ] = { en = "VARIATION SELECTOR-55", fr = "" },
  [ 0xE0127 ] = { en = "VARIATION SELECTOR-56", fr = "" },
  [ 0xE0128 ] = { en = "VARIATION SELECTOR-57", fr = "" },
  [ 0xE0129 ] = { en = "VARIATION SELECTOR-58", fr = "" },
  [ 0xE012A ] = { en = "VARIATION SELECTOR-59", fr = "" },
  [ 0xE012B ] = { en = "VARIATION SELECTOR-60", fr = "" },
  [ 0xE012C ] = { en = "VARIATION SELECTOR-61", fr = "" },
  [ 0xE012D ] = { en = "VARIATION SELECTOR-62", fr = "" },
  [ 0xE012E ] = { en = "VARIATION SELECTOR-63", fr = "" },
  [ 0xE012F ] = { en = "VARIATION SELECTOR-64", fr = "" },
  [ 0xE0130 ] = { en = "VARIATION SELECTOR-65", fr = "" },
  [ 0xE0131 ] = { en = "VARIATION SELECTOR-66", fr = "" },
  [ 0xE0132 ] = { en = "VARIATION SELECTOR-67", fr = "" },
  [ 0xE0133 ] = { en = "VARIATION SELECTOR-68", fr = "" },
  [ 0xE0134 ] = { en = "VARIATION SELECTOR-69", fr = "" },
  [ 0xE0135 ] = { en = "VARIATION SELECTOR-70", fr = "" },
  [ 0xE0136 ] = { en = "VARIATION SELECTOR-71", fr = "" },
  [ 0xE0137 ] = { en = "VARIATION SELECTOR-72", fr = "" },
  [ 0xE0138 ] = { en = "VARIATION SELECTOR-73", fr = "" },
  [ 0xE0139 ] = { en = "VARIATION SELECTOR-74", fr = "" },
  [ 0xE013A ] = { en = "VARIATION SELECTOR-75", fr = "" },
  [ 0xE013B ] = { en = "VARIATION SELECTOR-76", fr = "" },
  [ 0xE013C ] = { en = "VARIATION SELECTOR-77", fr = "" },
  [ 0xE013D ] = { en = "VARIATION SELECTOR-78", fr = "" },
  [ 0xE013E ] = { en = "VARIATION SELECTOR-79", fr = "" },
  [ 0xE013F ] = { en = "VARIATION SELECTOR-80", fr = "" },
  [ 0xE0140 ] = { en = "VARIATION SELECTOR-81", fr = "" },
  [ 0xE0141 ] = { en = "VARIATION SELECTOR-82", fr = "" },
  [ 0xE0142 ] = { en = "VARIATION SELECTOR-83", fr = "" },
  [ 0xE0143 ] = { en = "VARIATION SELECTOR-84", fr = "" },
  [ 0xE0144 ] = { en = "VARIATION SELECTOR-85", fr = "" },
  [ 0xE0145 ] = { en = "VARIATION SELECTOR-86", fr = "" },
  [ 0xE0146 ] = { en = "VARIATION SELECTOR-87", fr = "" },
  [ 0xE0147 ] = { en = "VARIATION SELECTOR-88", fr = "" },
  [ 0xE0148 ] = { en = "VARIATION SELECTOR-89", fr = "" },
  [ 0xE0149 ] = { en = "VARIATION SELECTOR-90", fr = "" },
  [ 0xE014A ] = { en = "VARIATION SELECTOR-91", fr = "" },
  [ 0xE014B ] = { en = "VARIATION SELECTOR-92", fr = "" },
  [ 0xE014C ] = { en = "VARIATION SELECTOR-93", fr = "" },
  [ 0xE014D ] = { en = "VARIATION SELECTOR-94", fr = "" },
  [ 0xE014E ] = { en = "VARIATION SELECTOR-95", fr = "" },
  [ 0xE014F ] = { en = "VARIATION SELECTOR-96", fr = "" },
  [ 0xE0150 ] = { en = "VARIATION SELECTOR-97", fr = "" },
  [ 0xE0151 ] = { en = "VARIATION SELECTOR-98", fr = "" },
  [ 0xE0152 ] = { en = "VARIATION SELECTOR-99", fr = "" },
  [ 0xE0153 ] = { en = "VARIATION SELECTOR-100", fr = "" },
  [ 0xE0154 ] = { en = "VARIATION SELECTOR-101", fr = "" },
  [ 0xE0155 ] = { en = "VARIATION SELECTOR-102", fr = "" },
  [ 0xE0156 ] = { en = "VARIATION SELECTOR-103", fr = "" },
  [ 0xE0157 ] = { en = "VARIATION SELECTOR-104", fr = "" },
  [ 0xE0158 ] = { en = "VARIATION SELECTOR-105", fr = "" },
  [ 0xE0159 ] = { en = "VARIATION SELECTOR-106", fr = "" },
  [ 0xE015A ] = { en = "VARIATION SELECTOR-107", fr = "" },
  [ 0xE015B ] = { en = "VARIATION SELECTOR-108", fr = "" },
  [ 0xE015C ] = { en = "VARIATION SELECTOR-109", fr = "" },
  [ 0xE015D ] = { en = "VARIATION SELECTOR-110", fr = "" },
  [ 0xE015E ] = { en = "VARIATION SELECTOR-111", fr = "" },
  [ 0xE015F ] = { en = "VARIATION SELECTOR-112", fr = "" },
  [ 0xE0160 ] = { en = "VARIATION SELECTOR-113", fr = "" },
  [ 0xE0161 ] = { en = "VARIATION SELECTOR-114", fr = "" },
  [ 0xE0162 ] = { en = "VARIATION SELECTOR-115", fr = "" },
  [ 0xE0163 ] = { en = "VARIATION SELECTOR-116", fr = "" },
  [ 0xE0164 ] = { en = "VARIATION SELECTOR-117", fr = "" },
  [ 0xE0165 ] = { en = "VARIATION SELECTOR-118", fr = "" },
  [ 0xE0166 ] = { en = "VARIATION SELECTOR-119", fr = "" },
  [ 0xE0167 ] = { en = "VARIATION SELECTOR-120", fr = "" },
  [ 0xE0168 ] = { en = "VARIATION SELECTOR-121", fr = "" },
  [ 0xE0169 ] = { en = "VARIATION SELECTOR-122", fr = "" },
  [ 0xE016A ] = { en = "VARIATION SELECTOR-123", fr = "" },
  [ 0xE016B ] = { en = "VARIATION SELECTOR-124", fr = "" },
  [ 0xE016C ] = { en = "VARIATION SELECTOR-125", fr = "" },
  [ 0xE016D ] = { en = "VARIATION SELECTOR-126", fr = "" },
  [ 0xE016E ] = { en = "VARIATION SELECTOR-127", fr = "" },
  [ 0xE016F ] = { en = "VARIATION SELECTOR-128", fr = "" },
  [ 0xE0170 ] = { en = "VARIATION SELECTOR-129", fr = "" },
  [ 0xE0171 ] = { en = "VARIATION SELECTOR-130", fr = "" },
  [ 0xE0172 ] = { en = "VARIATION SELECTOR-131", fr = "" },
  [ 0xE0173 ] = { en = "VARIATION SELECTOR-132", fr = "" },
  [ 0xE0174 ] = { en = "VARIATION SELECTOR-133", fr = "" },
  [ 0xE0175 ] = { en = "VARIATION SELECTOR-134", fr = "" },
  [ 0xE0176 ] = { en = "VARIATION SELECTOR-135", fr = "" },
  [ 0xE0177 ] = { en = "VARIATION SELECTOR-136", fr = "" },
  [ 0xE0178 ] = { en = "VARIATION SELECTOR-137", fr = "" },
  [ 0xE0179 ] = { en = "VARIATION SELECTOR-138", fr = "" },
  [ 0xE017A ] = { en = "VARIATION SELECTOR-139", fr = "" },
  [ 0xE017B ] = { en = "VARIATION SELECTOR-140", fr = "" },
  [ 0xE017C ] = { en = "VARIATION SELECTOR-141", fr = "" },
  [ 0xE017D ] = { en = "VARIATION SELECTOR-142", fr = "" },
  [ 0xE017E ] = { en = "VARIATION SELECTOR-143", fr = "" },
  [ 0xE017F ] = { en = "VARIATION SELECTOR-144", fr = "" },
  [ 0xE0180 ] = { en = "VARIATION SELECTOR-145", fr = "" },
  [ 0xE0181 ] = { en = "VARIATION SELECTOR-146", fr = "" },
  [ 0xE0182 ] = { en = "VARIATION SELECTOR-147", fr = "" },
  [ 0xE0183 ] = { en = "VARIATION SELECTOR-148", fr = "" },
  [ 0xE0184 ] = { en = "VARIATION SELECTOR-149", fr = "" },
  [ 0xE0185 ] = { en = "VARIATION SELECTOR-150", fr = "" },
  [ 0xE0186 ] = { en = "VARIATION SELECTOR-151", fr = "" },
  [ 0xE0187 ] = { en = "VARIATION SELECTOR-152", fr = "" },
  [ 0xE0188 ] = { en = "VARIATION SELECTOR-153", fr = "" },
  [ 0xE0189 ] = { en = "VARIATION SELECTOR-154", fr = "" },
  [ 0xE018A ] = { en = "VARIATION SELECTOR-155", fr = "" },
  [ 0xE018B ] = { en = "VARIATION SELECTOR-156", fr = "" },
  [ 0xE018C ] = { en = "VARIATION SELECTOR-157", fr = "" },
  [ 0xE018D ] = { en = "VARIATION SELECTOR-158", fr = "" },
  [ 0xE018E ] = { en = "VARIATION SELECTOR-159", fr = "" },
  [ 0xE018F ] = { en = "VARIATION SELECTOR-160", fr = "" },
  [ 0xE0190 ] = { en = "VARIATION SELECTOR-161", fr = "" },
  [ 0xE0191 ] = { en = "VARIATION SELECTOR-162", fr = "" },
  [ 0xE0192 ] = { en = "VARIATION SELECTOR-163", fr = "" },
  [ 0xE0193 ] = { en = "VARIATION SELECTOR-164", fr = "" },
  [ 0xE0194 ] = { en = "VARIATION SELECTOR-165", fr = "" },
  [ 0xE0195 ] = { en = "VARIATION SELECTOR-166", fr = "" },
  [ 0xE0196 ] = { en = "VARIATION SELECTOR-167", fr = "" },
  [ 0xE0197 ] = { en = "VARIATION SELECTOR-168", fr = "" },
  [ 0xE0198 ] = { en = "VARIATION SELECTOR-169", fr = "" },
  [ 0xE0199 ] = { en = "VARIATION SELECTOR-170", fr = "" },
  [ 0xE019A ] = { en = "VARIATION SELECTOR-171", fr = "" },
  [ 0xE019B ] = { en = "VARIATION SELECTOR-172", fr = "" },
  [ 0xE019C ] = { en = "VARIATION SELECTOR-173", fr = "" },
  [ 0xE019D ] = { en = "VARIATION SELECTOR-174", fr = "" },
  [ 0xE019E ] = { en = "VARIATION SELECTOR-175", fr = "" },
  [ 0xE019F ] = { en = "VARIATION SELECTOR-176", fr = "" },
  [ 0xE01A0 ] = { en = "VARIATION SELECTOR-177", fr = "" },
  [ 0xE01A1 ] = { en = "VARIATION SELECTOR-178", fr = "" },
  [ 0xE01A2 ] = { en = "VARIATION SELECTOR-179", fr = "" },
  [ 0xE01A3 ] = { en = "VARIATION SELECTOR-180", fr = "" },
  [ 0xE01A4 ] = { en = "VARIATION SELECTOR-181", fr = "" },
  [ 0xE01A5 ] = { en = "VARIATION SELECTOR-182", fr = "" },
  [ 0xE01A6 ] = { en = "VARIATION SELECTOR-183", fr = "" },
  [ 0xE01A7 ] = { en = "VARIATION SELECTOR-184", fr = "" },
  [ 0xE01A8 ] = { en = "VARIATION SELECTOR-185", fr = "" },
  [ 0xE01A9 ] = { en = "VARIATION SELECTOR-186", fr = "" },
  [ 0xE01AA ] = { en = "VARIATION SELECTOR-187", fr = "" },
  [ 0xE01AB ] = { en = "VARIATION SELECTOR-188", fr = "" },
  [ 0xE01AC ] = { en = "VARIATION SELECTOR-189", fr = "" },
  [ 0xE01AD ] = { en = "VARIATION SELECTOR-190", fr = "" },
  [ 0xE01AE ] = { en = "VARIATION SELECTOR-191", fr = "" },
  [ 0xE01AF ] = { en = "VARIATION SELECTOR-192", fr = "" },
  [ 0xE01B0 ] = { en = "VARIATION SELECTOR-193", fr = "" },
  [ 0xE01B1 ] = { en = "VARIATION SELECTOR-194", fr = "" },
  [ 0xE01B2 ] = { en = "VARIATION SELECTOR-195", fr = "" },
  [ 0xE01B3 ] = { en = "VARIATION SELECTOR-196", fr = "" },
  [ 0xE01B4 ] = { en = "VARIATION SELECTOR-197", fr = "" },
  [ 0xE01B5 ] = { en = "VARIATION SELECTOR-198", fr = "" },
  [ 0xE01B6 ] = { en = "VARIATION SELECTOR-199", fr = "" },
  [ 0xE01B7 ] = { en = "VARIATION SELECTOR-200", fr = "" },
  [ 0xE01B8 ] = { en = "VARIATION SELECTOR-201", fr = "" },
  [ 0xE01B9 ] = { en = "VARIATION SELECTOR-202", fr = "" },
  [ 0xE01BA ] = { en = "VARIATION SELECTOR-203", fr = "" },
  [ 0xE01BB ] = { en = "VARIATION SELECTOR-204", fr = "" },
  [ 0xE01BC ] = { en = "VARIATION SELECTOR-205", fr = "" },
  [ 0xE01BD ] = { en = "VARIATION SELECTOR-206", fr = "" },
  [ 0xE01BE ] = { en = "VARIATION SELECTOR-207", fr = "" },
  [ 0xE01BF ] = { en = "VARIATION SELECTOR-208", fr = "" },
  [ 0xE01C0 ] = { en = "VARIATION SELECTOR-209", fr = "" },
  [ 0xE01C1 ] = { en = "VARIATION SELECTOR-210", fr = "" },
  [ 0xE01C2 ] = { en = "VARIATION SELECTOR-211", fr = "" },
  [ 0xE01C3 ] = { en = "VARIATION SELECTOR-212", fr = "" },
  [ 0xE01C4 ] = { en = "VARIATION SELECTOR-213", fr = "" },
  [ 0xE01C5 ] = { en = "VARIATION SELECTOR-214", fr = "" },
  [ 0xE01C6 ] = { en = "VARIATION SELECTOR-215", fr = "" },
  [ 0xE01C7 ] = { en = "VARIATION SELECTOR-216", fr = "" },
  [ 0xE01C8 ] = { en = "VARIATION SELECTOR-217", fr = "" },
  [ 0xE01C9 ] = { en = "VARIATION SELECTOR-218", fr = "" },
  [ 0xE01CA ] = { en = "VARIATION SELECTOR-219", fr = "" },
  [ 0xE01CB ] = { en = "VARIATION SELECTOR-220", fr = "" },
  [ 0xE01CC ] = { en = "VARIATION SELECTOR-221", fr = "" },
  [ 0xE01CD ] = { en = "VARIATION SELECTOR-222", fr = "" },
  [ 0xE01CE ] = { en = "VARIATION SELECTOR-223", fr = "" },
  [ 0xE01CF ] = { en = "VARIATION SELECTOR-224", fr = "" },
  [ 0xE01D0 ] = { en = "VARIATION SELECTOR-225", fr = "" },
  [ 0xE01D1 ] = { en = "VARIATION SELECTOR-226", fr = "" },
  [ 0xE01D2 ] = { en = "VARIATION SELECTOR-227", fr = "" },
  [ 0xE01D3 ] = { en = "VARIATION SELECTOR-228", fr = "" },
  [ 0xE01D4 ] = { en = "VARIATION SELECTOR-229", fr = "" },
  [ 0xE01D5 ] = { en = "VARIATION SELECTOR-230", fr = "" },
  [ 0xE01D6 ] = { en = "VARIATION SELECTOR-231", fr = "" },
  [ 0xE01D7 ] = { en = "VARIATION SELECTOR-232", fr = "" },
  [ 0xE01D8 ] = { en = "VARIATION SELECTOR-233", fr = "" },
  [ 0xE01D9 ] = { en = "VARIATION SELECTOR-234", fr = "" },
  [ 0xE01DA ] = { en = "VARIATION SELECTOR-235", fr = "" },
  [ 0xE01DB ] = { en = "VARIATION SELECTOR-236", fr = "" },
  [ 0xE01DC ] = { en = "VARIATION SELECTOR-237", fr = "" },
  [ 0xE01DD ] = { en = "VARIATION SELECTOR-238", fr = "" },
  [ 0xE01DE ] = { en = "VARIATION SELECTOR-239", fr = "" },
  [ 0xE01DF ] = { en = "VARIATION SELECTOR-240", fr = "" },
  [ 0xE01E0 ] = { en = "VARIATION SELECTOR-241", fr = "" },
  [ 0xE01E1 ] = { en = "VARIATION SELECTOR-242", fr = "" },
  [ 0xE01E2 ] = { en = "VARIATION SELECTOR-243", fr = "" },
  [ 0xE01E3 ] = { en = "VARIATION SELECTOR-244", fr = "" },
  [ 0xE01E4 ] = { en = "VARIATION SELECTOR-245", fr = "" },
  [ 0xE01E5 ] = { en = "VARIATION SELECTOR-246", fr = "" },
  [ 0xE01E6 ] = { en = "VARIATION SELECTOR-247", fr = "" },
  [ 0xE01E7 ] = { en = "VARIATION SELECTOR-248", fr = "" },
  [ 0xE01E8 ] = { en = "VARIATION SELECTOR-249", fr = "" },
  [ 0xE01E9 ] = { en = "VARIATION SELECTOR-250", fr = "" },
  [ 0xE01EA ] = { en = "VARIATION SELECTOR-251", fr = "" },
  [ 0xE01EB ] = { en = "VARIATION SELECTOR-252", fr = "" },
  [ 0xE01EC ] = { en = "VARIATION SELECTOR-253", fr = "" },
  [ 0xE01ED ] = { en = "VARIATION SELECTOR-254", fr = "" },
  [ 0xE01EE ] = { en = "VARIATION SELECTOR-255", fr = "" },
  [ 0xE01EF ] = { en = "VARIATION SELECTOR-256", fr = "" },
  --]=]
}
